# Generated by Django 4.2.7 on 2023-11-25 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="name",
            field=models.CharField(default="measurements", max_length=100),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="measurement.sensor",
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
